<?php

use Illuminate\Database\Seeder;

class countriesTableSedder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
   		
	{



DB::table('countries')->insert(['code' =>  'AF', 'en' => 'Afghanistan']);
DB::table('countries')->insert(['code' =>  'AL', 'en' => 'Albania']);
DB::table('countries')->insert(['code' =>  'DZ', 'en' => 'Algeria']);
DB::table('countries')->insert(['code' =>  'DS', 'en' => 'American Samoa']);
DB::table('countries')->insert(['code' =>  'AD', 'en' => 'Andorra']);
DB::table('countries')->insert(['code' =>  'AO', 'en' => 'Angola']);
DB::table('countries')->insert(['code' =>  'AI', 'en' => 'Anguilla']);
DB::table('countries')->insert(['code' =>  'AQ', 'en' => 'Antarctica']);
DB::table('countries')->insert(['code' =>  'AG', 'en' => 'Antigua and Barbuda']);
DB::table('countries')->insert(['code' =>  'AR', 'en' => 'Argentina']);
DB::table('countries')->insert(['code' =>  'AM', 'en' => 'Armenia']);
DB::table('countries')->insert(['code' =>  'AW', 'en' => 'Aruba']);
DB::table('countries')->insert(['code' =>  'AU', 'en' => 'Australia']);
DB::table('countries')->insert(['code' =>  'AT', 'en' => 'Austria']);
DB::table('countries')->insert(['code' =>  'AZ', 'en' => 'Azerbaijan']);
DB::table('countries')->insert(['code' =>  'BS', 'en' => 'Bahamas']);
DB::table('countries')->insert(['code' =>  'BH', 'en' => 'Bahrain']);
DB::table('countries')->insert(['code' =>  'BD', 'en' => 'Bangladesh']);
DB::table('countries')->insert(['code' =>  'BB', 'en' => 'Barbados']);
DB::table('countries')->insert(['code' =>  'BY', 'en' => 'Belarus']);
DB::table('countries')->insert(['code' =>  'BE', 'en' => 'Belgium']);
DB::table('countries')->insert(['code' =>  'BZ', 'en' => 'Belize']);
DB::table('countries')->insert(['code' =>  'BJ', 'en' => 'Benin']);
DB::table('countries')->insert(['code' =>  'BM', 'en' => 'Bermuda']);
DB::table('countries')->insert(['code' =>  'BT', 'en' => 'Bhutan']);
DB::table('countries')->insert(['code' =>  'BO', 'en' => 'Bolivia']);
DB::table('countries')->insert(['code' =>  'BA', 'en' => 'Bosnia and Herzegovina']);
DB::table('countries')->insert(['code' =>  'BW', 'en' => 'Botswana']);
DB::table('countries')->insert(['code' =>  'BV', 'en' => 'Bouvet Island']);
DB::table('countries')->insert(['code' =>  'BR', 'en' => 'Brazil']);
DB::table('countries')->insert(['code' =>  'IO', 'en' => 'British Indian Ocean Territory']);
DB::table('countries')->insert(['code' =>  'BN', 'en' => 'Brunei Darussalam']);
DB::table('countries')->insert(['code' =>  'BG', 'en' => 'Bulgaria']);
DB::table('countries')->insert(['code' =>  'BF', 'en' => 'Burkina Faso']);
DB::table('countries')->insert(['code' =>  'BI', 'en' => 'Burundi']);
DB::table('countries')->insert(['code' =>  'KH', 'en' => 'Cambodia']);
DB::table('countries')->insert(['code' =>  'CM', 'en' => 'Cameroon']);
DB::table('countries')->insert(['code' =>  'CA', 'en' => 'Canada']);
DB::table('countries')->insert(['code' =>  'CV', 'en' => 'Cape Verde']);
DB::table('countries')->insert(['code' =>  'KY', 'en' => 'Cayman Islands']);
DB::table('countries')->insert(['code' =>  'CF', 'en' => 'Central African Republic']);
DB::table('countries')->insert(['code' =>  'TD', 'en' => 'Chad']);
DB::table('countries')->insert(['code' =>  'CL', 'en' => 'Chile']);
DB::table('countries')->insert(['code' =>  'CN', 'en' => 'China']);
DB::table('countries')->insert(['code' =>  'CX', 'en' => 'Christmas Island']);
DB::table('countries')->insert(['code' =>  'CC', 'en' => 'Cocos (Keeling) Islands']);
DB::table('countries')->insert(['code' =>  'CO', 'en' => 'Colombia']);
DB::table('countries')->insert(['code' =>  'KM', 'en' => 'Comoros']);
DB::table('countries')->insert(['code' =>  'CG', 'en' => 'Congo']);
DB::table('countries')->insert(['code' =>  'CK', 'en' => 'Cook Islands']);
DB::table('countries')->insert(['code' =>  'CR', 'en' => 'Costa Rica']);
DB::table('countries')->insert(['code' =>  'HR', 'en' => 'Croatia (Hrvatska)']);
DB::table('countries')->insert(['code' =>  'CU', 'en' => 'Cuba']);
DB::table('countries')->insert(['code' =>  'CY', 'en' => 'Cyprus']);
DB::table('countries')->insert(['code' =>  'CZ', 'en' => 'Czech Republic']);
DB::table('countries')->insert(['code' =>  'DK', 'en' => 'Denmark']);
DB::table('countries')->insert(['code' =>  'DJ', 'en' => 'Djibouti']);
DB::table('countries')->insert(['code' =>  'DM', 'en' => 'Dominica']);
DB::table('countries')->insert(['code' =>  'DO', 'en' => 'Dominican Republic']);
DB::table('countries')->insert(['code' =>  'TP', 'en' => 'East Timor']);
DB::table('countries')->insert(['code' =>  'EC', 'en' => 'Ecuador']);
DB::table('countries')->insert(['code' =>  'EG', 'en' => 'Egypt']);
DB::table('countries')->insert(['code' =>  'SV', 'en' => 'El Salvador']);
DB::table('countries')->insert(['code' =>  'GQ', 'en' => 'Equatorial Guinea']);
DB::table('countries')->insert(['code' =>  'ER', 'en' => 'Eritrea']);
DB::table('countries')->insert(['code' =>  'EE', 'en' => 'Estonia']);
DB::table('countries')->insert(['code' =>  'ET', 'en' => 'Ethiopia']);
DB::table('countries')->insert(['code' =>  'FK', 'en' => 'Falkland Islands (Malvinas)']);
DB::table('countries')->insert(['code' =>  'FO', 'en' => 'Faroe Islands']);
DB::table('countries')->insert(['code' =>  'FJ', 'en' => 'Fiji']);
DB::table('countries')->insert(['code' =>  'FI', 'en' => 'Finland']);
DB::table('countries')->insert(['code' =>  'FR', 'en' => 'France']);
DB::table('countries')->insert(['code' =>  'FX', 'en' => 'France, Metropolitan']);
DB::table('countries')->insert(['code' =>  'GF', 'en' => 'French Guiana']);
DB::table('countries')->insert(['code' =>  'PF', 'en' => 'French Polynesia']);
DB::table('countries')->insert(['code' =>  'TF', 'en' => 'French Southern Territories']);
DB::table('countries')->insert(['code' =>  'GA', 'en' => 'Gabon']);
DB::table('countries')->insert(['code' =>  'GM', 'en' => 'Gambia']);
DB::table('countries')->insert(['code' =>  'GE', 'en' => 'Georgia']);
DB::table('countries')->insert(['code' =>  'DE', 'en' => 'Germany']);
DB::table('countries')->insert(['code' =>  'GH', 'en' => 'Ghana']);
DB::table('countries')->insert(['code' =>  'GI', 'en' => 'Gibraltar']);
DB::table('countries')->insert(['code' =>  'GK', 'en' => 'Guernsey']);
DB::table('countries')->insert(['code' =>  'GR', 'en' => 'Greece']);
DB::table('countries')->insert(['code' =>  'GL', 'en' => 'Greenland']);
DB::table('countries')->insert(['code' =>  'GD', 'en' => 'Grenada']);
DB::table('countries')->insert(['code' =>  'GP', 'en' => 'Guadeloupe']);
DB::table('countries')->insert(['code' =>  'GU', 'en' => 'Guam']);
DB::table('countries')->insert(['code' =>  'GT', 'en' => 'Guatemala']);
DB::table('countries')->insert(['code' =>  'GN', 'en' => 'Guinea']);
DB::table('countries')->insert(['code' =>  'GW', 'en' => 'Guinea-Bissau']);
DB::table('countries')->insert(['code' =>  'GY', 'en' => 'Guyana']);
DB::table('countries')->insert(['code' =>  'HT', 'en' => 'Haiti']);
DB::table('countries')->insert(['code' =>  'HM', 'en' => 'Heard and Mc Donald Islands']);
DB::table('countries')->insert(['code' =>  'HN', 'en' => 'Honduras']);
DB::table('countries')->insert(['code' =>  'HK', 'en' => 'Hong Kong']);
DB::table('countries')->insert(['code' =>  'HU', 'en' => 'Hungary']);
DB::table('countries')->insert(['code' =>  'IS', 'en' => 'Iceland']);
DB::table('countries')->insert(['code' =>  'IN', 'en' => 'India']);
DB::table('countries')->insert(['code' =>  'IM', 'en' => 'Isle of Man']);
DB::table('countries')->insert(['code' =>  'ID', 'en' => 'Indonesia']);
DB::table('countries')->insert(['code' =>  'IR', 'en' => 'Iran']);
DB::table('countries')->insert(['code' =>  'IQ', 'en' => 'Iraq']);
DB::table('countries')->insert(['code' =>  'IE', 'en' => 'Ireland']);
DB::table('countries')->insert(['code' =>  'IL', 'en' => 'Israel']);
DB::table('countries')->insert(['code' =>  'IT', 'en' => 'Italy']);
DB::table('countries')->insert(['code' =>  'CI', 'en' => 'Ivory Coast']);
DB::table('countries')->insert(['code' =>  'JE', 'en' => 'Jersey']);
DB::table('countries')->insert(['code' =>  'JM', 'en' => 'Jamaica']);
DB::table('countries')->insert(['code' =>  'JP', 'en' => 'Japan']);
DB::table('countries')->insert(['code' =>  'JO', 'en' => 'Jordan']);
DB::table('countries')->insert(['code' =>  'KZ', 'en' => 'Kazakhstan']);
DB::table('countries')->insert(['code' =>  'KE', 'en' => 'Kenya']);
DB::table('countries')->insert(['code' =>  'KI', 'en' => 'Kiribati']);
DB::table('countries')->insert(['code' =>  'KP', 'en' => 'Korea, Democratic People\'s Republic of']);
DB::table('countries')->insert(['code' =>  'KR', 'en' => 'Korea, Republic of']);
DB::table('countries')->insert(['code' =>  'XK', 'en' => 'Kosovo']);
DB::table('countries')->insert(['code' =>  'KW', 'en' => 'Kuwait']);
DB::table('countries')->insert(['code' =>  'KG', 'en' => 'Kyrgyzstan']);
DB::table('countries')->insert(['code' =>  'LA', 'en' => 'Lao People\'s Democratic Republic']);
DB::table('countries')->insert(['code' =>  'LV', 'en' => 'Latvia']);
DB::table('countries')->insert(['code' =>  'LB', 'en' => 'Lebanon']);
DB::table('countries')->insert(['code' =>  'LS', 'en' => 'Lesotho']);
DB::table('countries')->insert(['code' =>  'LR', 'en' => 'Liberia']);
DB::table('countries')->insert(['code' =>  'LY', 'en' => 'Libyan Arab Jamahiriya']);
DB::table('countries')->insert(['code' =>  'LI', 'en' => 'Liechtenstein']);
DB::table('countries')->insert(['code' =>  'LT', 'en' => 'Lithuania']);
DB::table('countries')->insert(['code' =>  'LU', 'en' => 'Luxembourg']);
DB::table('countries')->insert(['code' =>  'MO', 'en' => 'Macau']);
DB::table('countries')->insert(['code' =>  'MK', 'en' => 'Macedonia']);
DB::table('countries')->insert(['code' =>  'MG', 'en' => 'Madagascar']);
DB::table('countries')->insert(['code' =>  'MW', 'en' => 'Malawi']);
DB::table('countries')->insert(['code' =>  'MY', 'en' => 'Malaysia']);
DB::table('countries')->insert(['code' =>  'MV', 'en' => 'Maldives']);
DB::table('countries')->insert(['code' =>  'ML', 'en' => 'Mali']);
DB::table('countries')->insert(['code' =>  'MT', 'en' => 'Malta']);
DB::table('countries')->insert(['code' =>  'MH', 'en' => 'Marshall Islands']);
DB::table('countries')->insert(['code' =>  'MQ', 'en' => 'Martinique']);
DB::table('countries')->insert(['code' =>  'MR', 'en' => 'Mauritania']);
DB::table('countries')->insert(['code' =>  'MU', 'en' => 'Mauritius']);
DB::table('countries')->insert(['code' =>  'TY', 'en' => 'Mayotte']);
DB::table('countries')->insert(['code' =>  'MX', 'en' => 'Mexico']);
DB::table('countries')->insert(['code' =>  'FM', 'en' => 'Micronesia, Federated States of']);
DB::table('countries')->insert(['code' =>  'MD', 'en' => 'Moldova, Republic of']);
DB::table('countries')->insert(['code' =>  'MC', 'en' => 'Monaco']);
DB::table('countries')->insert(['code' =>  'MN', 'en' => 'Mongolia']);
DB::table('countries')->insert(['code' =>  'ME', 'en' => 'Montenegro']);
DB::table('countries')->insert(['code' =>  'MS', 'en' => 'Montserrat']);
DB::table('countries')->insert(['code' =>  'MA', 'en' => 'Morocco']);
DB::table('countries')->insert(['code' =>  'MZ', 'en' => 'Mozambique']);
DB::table('countries')->insert(['code' =>  'MM', 'en' => 'Myanmar']);
DB::table('countries')->insert(['code' =>  'NA', 'en' => 'Namibia']);
DB::table('countries')->insert(['code' =>  'NR', 'en' => 'Nauru']);
DB::table('countries')->insert(['code' =>  'NP', 'en' => 'Nepal']);
DB::table('countries')->insert(['code' =>  'NL', 'en' => 'Netherlands']);
DB::table('countries')->insert(['code' =>  'AN', 'en' => 'Netherlands Antilles']);
DB::table('countries')->insert(['code' =>  'NC', 'en' => 'New Caledonia']);
DB::table('countries')->insert(['code' =>  'NZ', 'en' => 'New Zealand']);
DB::table('countries')->insert(['code' =>  'NI', 'en' => 'Nicaragua']);
DB::table('countries')->insert(['code' =>  'NE', 'en' => 'Niger']);
DB::table('countries')->insert(['code' =>  'NG', 'en' => 'Nigeria']);
DB::table('countries')->insert(['code' =>  'NU', 'en' => 'Niue']);
DB::table('countries')->insert(['code' =>  'NF', 'en' => 'Norfolk Island']);
DB::table('countries')->insert(['code' =>  'MP', 'en' => 'Northern Mariana Islands']);
DB::table('countries')->insert(['code' =>  'NO', 'en' => 'Norway']);
DB::table('countries')->insert(['code' =>  'OM', 'en' => 'Oman']);
DB::table('countries')->insert(['code' =>  'PK', 'en' => 'Pakistan']);
DB::table('countries')->insert(['code' =>  'PW', 'en' => 'Palau']);
DB::table('countries')->insert(['code' =>  'PS', 'en' => 'Palestine']);
DB::table('countries')->insert(['code' =>  'PA', 'en' => 'Panama']);
DB::table('countries')->insert(['code' =>  'PG', 'en' => 'Papua New Guinea']);
DB::table('countries')->insert(['code' =>  'PY', 'en' => 'Paraguay']);
DB::table('countries')->insert(['code' =>  'PE', 'en' => 'Peru']);
DB::table('countries')->insert(['code' =>  'PH', 'en' => 'Philippines']);
DB::table('countries')->insert(['code' =>  'PN', 'en' => 'Pitcairn']);
DB::table('countries')->insert(['code' =>  'PL', 'en' => 'Poland']);
DB::table('countries')->insert(['code' =>  'PT', 'en' => 'Portugal']);
DB::table('countries')->insert(['code' =>  'PR', 'en' => 'Puerto Rico']);
DB::table('countries')->insert(['code' =>  'QA', 'en' => 'Qatar']);
DB::table('countries')->insert(['code' =>  'RE', 'en' => 'Reunion']);
DB::table('countries')->insert(['code' =>  'RO', 'en' => 'Romania']);
DB::table('countries')->insert(['code' =>  'RU', 'en' => 'Russian Federation']);
DB::table('countries')->insert(['code' =>  'RW', 'en' => 'Rwanda']);
DB::table('countries')->insert(['code' =>  'KN', 'en' => 'Saint Kitts and Nevis']);
DB::table('countries')->insert(['code' =>  'LC', 'en' => 'Saint Lucia']);
DB::table('countries')->insert(['code' =>  'VC', 'en' => 'Saint Vincent and the Grenadines']);
DB::table('countries')->insert(['code' =>  'WS', 'en' => 'Samoa']);
DB::table('countries')->insert(['code' =>  'SM', 'en' => 'San Marino']);
DB::table('countries')->insert(['code' =>  'ST', 'en' => 'Sao Tome and Principe']);
DB::table('countries')->insert(['code' =>  'SA', 'en' => 'Saudi Arabia']);
DB::table('countries')->insert(['code' =>  'SN', 'en' => 'Senegal']);
DB::table('countries')->insert(['code' =>  'RS', 'en' => 'Serbia']);
DB::table('countries')->insert(['code' =>  'SC', 'en' => 'Seychelles']);
DB::table('countries')->insert(['code' =>  'SL', 'en' => 'Sierra Leone']);
DB::table('countries')->insert(['code' =>  'SG', 'en' => 'Singapore']);
DB::table('countries')->insert(['code' =>  'SK', 'en' => 'Slovakia']);
DB::table('countries')->insert(['code' =>  'SI', 'en' => 'Slovenia']);
DB::table('countries')->insert(['code' =>  'SB', 'en' => 'Solomon Islands']);
DB::table('countries')->insert(['code' =>  'SO', 'en' => 'Somalia']);
DB::table('countries')->insert(['code' =>  'ZA', 'en' => 'South Africa']);
DB::table('countries')->insert(['code' =>  'GS', 'en' => 'South Georgia South Sandwich Islands']);
DB::table('countries')->insert(['code' =>  'ES', 'en' => 'Spain']);
DB::table('countries')->insert(['code' =>  'LK', 'en' => 'Sri Lanka']);
DB::table('countries')->insert(['code' =>  'SH', 'en' => 'St. Helena']);
DB::table('countries')->insert(['code' =>  'PM', 'en' => 'St. Pierre and Miquelon']);
DB::table('countries')->insert(['code' =>  'SD', 'en' => 'Sudan']);
DB::table('countries')->insert(['code' =>  'SR', 'en' => 'Suriname']);
DB::table('countries')->insert(['code' =>  'SJ', 'en' => 'Svalbard and Jan Mayen Islands']);
DB::table('countries')->insert(['code' =>  'SZ', 'en' => 'Swaziland']);
DB::table('countries')->insert(['code' =>  'SE', 'en' => 'Sweden']);
DB::table('countries')->insert(['code' =>  'CH', 'en' => 'Switzerland']);
DB::table('countries')->insert(['code' =>  'SY', 'en' => 'Syrian Arab Republic']);
DB::table('countries')->insert(['code' =>  'TW', 'en' => 'Taiwan']);
DB::table('countries')->insert(['code' =>  'TJ', 'en' => 'Tajikistan']);
DB::table('countries')->insert(['code' =>  'TZ', 'en' => 'Tanzania, United Republic of']);
DB::table('countries')->insert(['code' =>  'TH', 'en' => 'Thailand']);
DB::table('countries')->insert(['code' =>  'TG', 'en' => 'Togo']);
DB::table('countries')->insert(['code' =>  'TK', 'en' => 'Tokelau']);
DB::table('countries')->insert(['code' =>  'TO', 'en' => 'Tonga']);
DB::table('countries')->insert(['code' =>  'TT', 'en' => 'Trinidad and Tobago']);
DB::table('countries')->insert(['code' =>  'TN', 'en' => 'Tunisia']);
DB::table('countries')->insert(['code' =>  'TR', 'en' => 'Turkey']);
DB::table('countries')->insert(['code' =>  'TM', 'en' => 'Turkmenistan']);
DB::table('countries')->insert(['code' =>  'TC', 'en' => 'Turks and Caicos Islands']);
DB::table('countries')->insert(['code' =>  'TV', 'en' => 'Tuvalu']);
DB::table('countries')->insert(['code' =>  'UG', 'en' => 'Uganda']);
DB::table('countries')->insert(['code' =>  'UA', 'en' => 'Ukraine']);
DB::table('countries')->insert(['code' =>  'AE', 'en' => 'United Arab Emirates']);
DB::table('countries')->insert(['code' =>  'GB', 'en' => 'United Kingdom']);
DB::table('countries')->insert(['code' =>  'US', 'en' => 'United States']);
DB::table('countries')->insert(['code' =>  'UM', 'en' => 'United States minor outlying islands']);
DB::table('countries')->insert(['code' =>  'UY', 'en' => 'Uruguay']);
DB::table('countries')->insert(['code' =>  'UZ', 'en' => 'Uzbekistan']);
DB::table('countries')->insert(['code' =>  'VU', 'en' => 'Vanuatu']);
DB::table('countries')->insert(['code' =>  'VA', 'en' => 'Vatican City State']);
DB::table('countries')->insert(['code' =>  'VE', 'en' => 'Venezuela']);
DB::table('countries')->insert(['code' =>  'VN', 'en' => 'Vietnam']);
DB::table('countries')->insert(['code' =>  'VG', 'en' => 'Virgin Islands (British)']);
DB::table('countries')->insert(['code' =>  'VI', 'en' => 'Virgin Islands (U.S.)']);
DB::table('countries')->insert(['code' =>  'WF', 'en' => 'Wallis and Futuna Islands']);
DB::table('countries')->insert(['code' =>  'EH', 'en' => 'Western Sahara']);
DB::table('countries')->insert(['code' =>  'YE', 'en' => 'Yemen']);
DB::table('countries')->insert(['code' =>  'ZR', 'en' => 'Zaire']);
DB::table('countries')->insert(['code' =>  'ZM', 'en' => 'Zambia']);
DB::table('countries')->insert(['code' =>  'ZW', 'en' => 'Zimbabwe']);



    }
}
